// Package kernel_boot demonstrates the simplest vmtest_config pattern:
// boot a VM, run commands, verify output.
//
// All tests share a single VM (booted once via the first vmconfig.New call).
// Subtests run sequentially against the same guest, avoiding repeated boot overhead.
package kernel_boot

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	// vmconfig is generated by the vmtest_config rule in BUILD.bazel.
	// Importing it sets VMTEST_* env vars via init(), and provides New().
	"rules_vmtest/examples/kernel_boot/vmconfig"
)

func TestKernelBoot(t *testing.T) {
	m := vmconfig.New(t)

	t.Run("KernelVersion", func(t *testing.T) {
		out := m.Succeed(t, "uname -r")
		if strings.TrimSpace(out) == "" {
			t.Fatal("uname -r returned empty")
		}
		t.Logf("kernel: %s", strings.TrimSpace(out))
	})

	t.Run("CommandExecution", func(t *testing.T) {
		stdout, stderr, code, err := m.Execute("echo out && echo err >&2")
		if err != nil {
			t.Fatalf("Execute: %v", err)
		}
		if code != 0 {
			t.Fatalf("exit code %d, stderr: %s", code, stderr)
		}
		if strings.TrimSpace(stdout) != "out" {
			t.Errorf("stdout: got %q", stdout)
		}
	})

	t.Run("NonZeroExitCode", func(t *testing.T) {
		_, _, code, err := m.Execute("exit 42")
		if err != nil {
			t.Fatalf("Execute: %v", err)
		}
		if code != 42 {
			t.Errorf("exit code: got %d, want 42", code)
		}
	})

	t.Run("FailExpectsNonZero", func(t *testing.T) {
		m.Fail(t, "false")
	})

	t.Run("FileOperations", func(t *testing.T) {
		hostFile := filepath.Join(t.TempDir(), "greeting.txt")
		if err := os.WriteFile(hostFile, []byte("hello from host"), 0644); err != nil {
			t.Fatal(err)
		}
		m.CopyFromHost(t, hostFile, "/tmp/greeting.txt")

		out := m.Succeed(t, "cat /tmp/greeting.txt")
		if out != "hello from host" {
			t.Fatalf("got %q, want %q", out, "hello from host")
		}
	})

	t.Run("WaitForFile", func(t *testing.T) {
		m.Succeed(t, "touch /tmp/marker")
		m.WaitForFile(t, "/tmp/marker")
	})
}
