name: Publish to BCR

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  publish:
    uses: bazel-contrib/publish-to-bcr/.github/workflows/publish.yaml@main
    with:
      tag_name: ${{ github.event.release.tag_name }}
      registry_fork: mikn/bazel-central-registry
    secrets:
      publish_token: ${{ secrets.BCR_PUBLISH_TOKEN }}
